// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qUVTwKyRdm4aph4nMY1fSY6KQ0N2SJ4',
    appId: '1:887685789721:web:376ac3daa2c3b555839288',
    messagingSenderId: '887685789721',
    projectId: 'e-enforcement-e09c6',
    authDomain: 'e-enforcement-e09c6.firebaseapp.com',
    storageBucket: 'e-enforcement-e09c6.firebasestorage.app',
    measurementId: 'G-1TTQF4Z1PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgmqNxJDUyPymWEbHBwEcdlGV7CS5WeKo',
    appId: '1:887685789721:android:bce404a56136ef6e839288',
    messagingSenderId: '887685789721',
    projectId: 'e-enforcement-e09c6',
    storageBucket: 'e-enforcement-e09c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRF3u8sMZmyR3YjJXiH5py6SzD0hy_i4',
    appId: '1:887685789721:ios:9924877cdeed9dc6839288',
    messagingSenderId: '887685789721',
    projectId: 'e-enforcement-e09c6',
    storageBucket: 'e-enforcement-e09c6.firebasestorage.app',
    iosBundleId: 'com.pitb.gov.egreenpunjab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRF3u8sMZmyR3YjJXiH5py6SzD0hy_i4',
    appId: '1:887685789721:ios:bb7870c09f69cdfb839288',
    messagingSenderId: '887685789721',
    projectId: 'e-enforcement-e09c6',
    storageBucket: 'e-enforcement-e09c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7qUVTwKyRdm4aph4nMY1fSY6KQ0N2SJ4',
    appId: '1:887685789721:web:fe48bfac59b385ec839288',
    messagingSenderId: '887685789721',
    projectId: 'e-enforcement-e09c6',
    authDomain: 'e-enforcement-e09c6.firebaseapp.com',
    storageBucket: 'e-enforcement-e09c6.firebasestorage.app',
    measurementId: 'G-CHS7N72M44',
  );

}